# Generated by Django 3.2.14 on 2022-07-17 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receptionist', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Receptionist',
        ),
    ]
