# Generated by Django 3.2.14 on 2022-07-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='hospital.user')),
                ('address', models.TextField()),
                ('speciality', models.CharField(max_length=50)),
            ],
        ),
    ]
